stages:
  - build
  - test

# Сборка контейнера с приложением
build_app:
  stage: build
  script:
    - docker-compose build app

# Сборка контейнера с тестами
build_test:
  stage: build
  script:
    - docker-compose build test

# Запуск тестов
test:
  stage: test
  script:
    - docker-compose up -d app
    - docker-compose run test_container
  dependencies:
    - build_app
    - build_test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production